//! Bash shell hook for Tabra.
//!
//! Uses bash's programmable completion (`complete -D -F`) for Tab acceptance,
//! `bind -x` for keystroke interception, and ANSI escape sequences for the
//! popup overlay. Requires bash 4.0+.
//!
//! The hook script is printed to stdout and eval'd by the user's .bashrc:
//!   eval "$(tabra init bash)"

/// Generate the bash hook script.
pub fn bash_hook() -> String {
    r##"
# ============================================================================
# Tabra - Terminal Autocomplete Hook for Bash
# Generated by: tabra init bash
# Add to .bashrc: eval "$(tabra init bash)"
# Requires: bash 4.0+ (for READLINE_LINE, READLINE_POINT, bind -x)
# ============================================================================

# Guard against double-sourcing
[[ -n "$_TABRA_LOADED" ]] && return
_TABRA_LOADED=1

# Check bash version (need 4.0+ for READLINE_LINE)
if ((BASH_VERSINFO[0] < 4)); then
    echo "tabra: requires bash 4.0+ (found ${BASH_VERSION})" >&2
    return
fi

# State variables
_TABRA_POPUP_VISIBLE=0
_TABRA_POPUP_LINES=0
_TABRA_SELECTED=0
_TABRA_ITEM_COUNT=0
_TABRA_DISPLAYS=()
_TABRA_INSERTS=()
_TABRA_DESCS=()
_TABRA_RENDERED_POPUP=""

# Ensure daemon is running
_tabra_ensure_daemon() {
    tabra status &>/dev/null && return
    tabra daemon &>/dev/null &
    disown
    local i
    for i in 1 2 3 4 5; do
        sleep 0.1
        tabra status &>/dev/null && return
    done
}

# Erase the popup overlay
_tabra_erase_popup() {
    if (( _TABRA_POPUP_VISIBLE )); then
        local i
        for (( i = 0; i < _TABRA_POPUP_LINES + 2; i++ )); do
            printf '\n\r\033[2K'
        done
        printf "\033[%dA" $(( _TABRA_POPUP_LINES + 2 ))
        _TABRA_POPUP_VISIBLE=0
        _TABRA_POPUP_LINES=0
    fi
}

# Parse tab-delimited response from tabra complete-shell
_tabra_parse_response() {
    _TABRA_DISPLAYS=()
    _TABRA_INSERTS=()
    _TABRA_DESCS=()
    _TABRA_ITEM_COUNT=0

    local -a lines
    mapfile -t lines <<< "$1"

    (( ${#lines[@]} < 1 )) && return
    _TABRA_ITEM_COUNT=${lines[0]}
    (( _TABRA_ITEM_COUNT == 0 )) && return

    local i
    for (( i = 1; i < ${#lines[@]} && i <= _TABRA_ITEM_COUNT; i++ )); do
        local line="${lines[$i]}"
        local display="${line%%	*}"
        local rest="${line#*	}"
        local insert="${rest%%	*}"
        local desc=""
        if [[ "$rest" == *$'\t'* ]]; then
            desc="${rest#*	}"
        fi

        _TABRA_DISPLAYS+=("$display")
        _TABRA_INSERTS+=("$insert")
        _TABRA_DESCS+=("$desc")
    done
}

# Render the popup
_tabra_render_popup() {
    _tabra_erase_popup

    (( _TABRA_ITEM_COUNT == 0 )) && return

    _TABRA_POPUP_VISIBLE=1
    local visible=$(( _TABRA_ITEM_COUNT < 10 ? _TABRA_ITEM_COUNT : 10 ))
    _TABRA_POPUP_LINES=$visible

    # Use pre-rendered ANSI popup if available and selection is 0
    if [[ -n "$_TABRA_RENDERED_POPUP" ]] && (( _TABRA_SELECTED == 0 )); then
        printf '%s' "$_TABRA_RENDERED_POPUP"
        return
    fi

    # Fallback: basic rendering
    printf '\n'
    local i
    for (( i = 0; i < visible; i++ )); do
        local display="${_TABRA_DISPLAYS[$i]}"
        local desc="${_TABRA_DESCS[$i]}"

        if (( i == _TABRA_SELECTED )); then
            if [[ -n "$desc" ]]; then
                printf '\r\033[7m %s  \033[2m%s\033[22m \033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r\033[7m %s \033[0m\033[K\n' "$display"
            fi
        else
            if [[ -n "$desc" ]]; then
                printf '\r  %s  \033[90m%s\033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r  %s \033[K\n' "$display"
            fi
        fi
    done
    printf "\033[%dA" $(( visible + 1 ))
}

# Fetch completions from daemon and render
_tabra_fetch_and_render() {
    local response
    response=$(tabra complete-shell --buffer "$READLINE_LINE" --cursor "$READLINE_POINT" --cwd "$PWD" --cols "${COLUMNS:-80}" --render 2>/dev/null)

    if [[ -z "$response" ]]; then
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
        _TABRA_RENDERED_POPUP=""
        return
    fi

    _TABRA_SELECTED=0

    # Split response: items section (before blank line) and rendered popup (after)
    local items_section="${response%%$'\n\n'*}"
    if [[ "$response" == *$'\n\n'* ]]; then
        _TABRA_RENDERED_POPUP="${response#*$'\n\n'}"
    else
        _TABRA_RENDERED_POPUP=""
    fi

    _tabra_parse_response "$items_section"

    if (( _TABRA_ITEM_COUNT == 0 )); then
        _tabra_erase_popup
        return
    fi

    _tabra_render_popup
}

# Accept the currently selected suggestion
_tabra_accept() {
    if (( _TABRA_POPUP_VISIBLE && _TABRA_ITEM_COUNT > 0 )); then
        local insert_text="${_TABRA_INSERTS[$_TABRA_SELECTED]}"
        if [[ -n "$insert_text" ]]; then
            # Find the current token boundary by forward walk (quote-aware)
            local before_cursor="${READLINE_LINE:0:$READLINE_POINT}"
            local after_cursor="${READLINE_LINE:$READLINE_POINT}"
            local token_start=0

            local -i pos=0 last_boundary=0
            local in_sq=0 in_dq=0 escape_next=0
            local ch
            while (( pos < ${#before_cursor} )); do
                ch="${before_cursor:$pos:1}"
                if (( escape_next )); then
                    (( escape_next = 0 ))
                elif [[ "$ch" == '\' ]] && (( !in_sq )); then
                    (( escape_next = 1 ))
                elif [[ "$ch" == "'" ]] && (( !in_dq )); then
                    (( in_sq = !in_sq ))
                elif [[ "$ch" == '"' ]] && (( !in_sq )); then
                    (( in_dq = !in_dq ))
                elif [[ "$ch" == ' ' || "$ch" == $'\t' ]] && (( !in_sq && !in_dq )); then
                    last_boundary=$(( pos + 1 ))
                fi
                (( pos++ ))
            done
            token_start=$last_boundary

            READLINE_LINE="${READLINE_LINE:0:$token_start}${insert_text} ${after_cursor}"
            READLINE_POINT=$(( token_start + ${#insert_text} + 1 ))
            tabra accept --text "$insert_text" &>/dev/null &
            disown
        fi
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
        _TABRA_RENDERED_POPUP=""
    else
        # No popup visible: do normal Tab completion
        # Re-enable default readline completion for this keypress
        return 1
    fi
}

# Navigate up (Ctrl+P)
_tabra_up() {
    if (( _TABRA_POPUP_VISIBLE )); then
        (( _TABRA_SELECTED = (_TABRA_SELECTED - 1 + _TABRA_ITEM_COUNT) % _TABRA_ITEM_COUNT ))
        _tabra_render_popup
    fi
}

# Navigate down (Ctrl+N)
_tabra_down() {
    if (( _TABRA_POPUP_VISIBLE )); then
        (( _TABRA_SELECTED = (_TABRA_SELECTED + 1) % _TABRA_ITEM_COUNT ))
        _tabra_render_popup
    fi
}

# Dismiss the popup (Escape)
_tabra_dismiss() {
    if (( _TABRA_POPUP_VISIBLE )); then
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
        _TABRA_RENDERED_POPUP=""
        tabra dismiss &>/dev/null &
        disown
    fi
}

# Self-insert: type a character then fetch completions
_tabra_self_insert() {
    local char="$1"
    if [[ -n "$char" ]]; then
        local before="${READLINE_LINE:0:$READLINE_POINT}"
        local after="${READLINE_LINE:$READLINE_POINT}"
        READLINE_LINE="${before}${char}${after}"
        (( READLINE_POINT += ${#char} ))
    fi
    _tabra_fetch_and_render
}

# Backward delete with popup update
_tabra_backward_delete() {
    if (( READLINE_POINT > 0 )); then
        local before="${READLINE_LINE:0:$((READLINE_POINT - 1))}"
        local after="${READLINE_LINE:$READLINE_POINT}"
        READLINE_LINE="${before}${after}"
        (( READLINE_POINT-- ))
    fi
    if [[ -n "$READLINE_LINE" ]]; then
        _tabra_fetch_and_render
    else
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
    fi
}

# Clean up popup before command execution.
# This runs via PROMPT_COMMAND before the next prompt is drawn,
# ensuring the popup is erased after Enter or any command execution.
_tabra_pre_prompt() {
    _tabra_erase_popup
    _TABRA_ITEM_COUNT=0
    _TABRA_RENDERED_POPUP=""
}

# Append our pre-prompt cleanup (don't overwrite existing PROMPT_COMMAND)
if [[ -z "$PROMPT_COMMAND" ]]; then
    PROMPT_COMMAND="_tabra_pre_prompt"
elif [[ "$PROMPT_COMMAND" != *"_tabra_pre_prompt"* ]]; then
    PROMPT_COMMAND="_tabra_pre_prompt;${PROMPT_COMMAND}"
fi

# ---- Key Bindings ----
# Tab: accept suggestion (via bind -x, overrides default completion)
bind -x '"\C-i": _tabra_accept'

# Ctrl+N / Ctrl+P: navigate popup (these don't conflict with arrow keys)
bind -x '"\C-n": _tabra_down'
bind -x '"\C-p": _tabra_up'

# Escape: dismiss popup
bind -x '"\C-g": _tabra_dismiss'

# Backspace: delete + refresh
bind -x '"\C-?": _tabra_backward_delete'

# Bind printable characters to self-insert + fetch
_tabra_bind_chars() {
    local chars="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    chars+="-./_~:=+@!#%"
    chars+=" "
    local i
    for (( i = 0; i < ${#chars}; i++ )); do
        local c="${chars:$i:1}"
        bind -x "\"$c\": _tabra_self_insert '$c'"
    done
}
_tabra_bind_chars

# Ensure daemon on shell startup
_tabra_ensure_daemon

# Cleanup on exit
trap '_tabra_erase_popup' EXIT
"##
    .to_string()
}
