//! Fish shell hook for Tabra.
//!
//! Uses `bind` for key bindings and `commandline` for buffer access.
//! Fish has cleaner variable scoping and key binding than bash.
//!
//! The hook script is printed to stdout and eval'd by the user's config.fish:
//!   tabra init fish | source

/// Generate the fish hook script.
pub fn fish_hook() -> String {
    r##"
# ============================================================================
# Tabra - Terminal Autocomplete Hook for Fish
# Generated by: tabra init fish
# Add to config.fish: tabra init fish | source
# ============================================================================

# Guard against double-sourcing
if set -q _TABRA_LOADED
    return
end
set -g _TABRA_LOADED 1

# State variables
set -g _TABRA_POPUP_VISIBLE 0
set -g _TABRA_POPUP_LINES 0
set -g _TABRA_SELECTED 0
set -g _TABRA_ITEM_COUNT 0
set -g _TABRA_DISPLAYS
set -g _TABRA_INSERTS
set -g _TABRA_DESCS
set -g _TABRA_RENDERED_POPUP ""

# Ensure daemon is running
function _tabra_ensure_daemon
    tabra status &>/dev/null; and return
    tabra daemon &>/dev/null &
    disown
    for i in (seq 5)
        sleep 0.1
        tabra status &>/dev/null; and return
    end
end

# Erase the popup overlay
function _tabra_erase_popup
    if test $_TABRA_POPUP_VISIBLE -eq 1
        for i in (seq (math "$_TABRA_POPUP_LINES + 2"))
            printf '\n\r\033[2K'
        end
        printf "\033[%dA" (math "$_TABRA_POPUP_LINES + 2")
        set -g _TABRA_POPUP_VISIBLE 0
        set -g _TABRA_POPUP_LINES 0
    end
end

# Parse tab-delimited response
function _tabra_parse_response
    set -g _TABRA_DISPLAYS
    set -g _TABRA_INSERTS
    set -g _TABRA_DESCS
    set -g _TABRA_ITEM_COUNT 0

    set -l lines (string split \n -- $argv[1])

    if test (count $lines) -lt 1
        return
    end

    set -g _TABRA_ITEM_COUNT $lines[1]
    if test $_TABRA_ITEM_COUNT -eq 0
        return
    end

    for i in (seq 2 (count $lines))
        if test (math "$i - 1") -gt $_TABRA_ITEM_COUNT
            break
        end
        set -l line $lines[$i]
        set -l parts (string split \t -- $line)
        set -a _TABRA_DISPLAYS $parts[1]
        if test (count $parts) -ge 2
            set -a _TABRA_INSERTS $parts[2]
        else
            set -a _TABRA_INSERTS $parts[1]
        end
        if test (count $parts) -ge 3
            set -a _TABRA_DESCS $parts[3]
        else
            set -a _TABRA_DESCS ""
        end
    end
end

# Render the popup
function _tabra_render_popup
    _tabra_erase_popup

    if test $_TABRA_ITEM_COUNT -eq 0
        return
    end

    set -g _TABRA_POPUP_VISIBLE 1
    set -l visible (math "min($_TABRA_ITEM_COUNT, 10)")
    set -g _TABRA_POPUP_LINES $visible

    # Use pre-rendered popup if available and selection is 0
    if test -n "$_TABRA_RENDERED_POPUP"; and test $_TABRA_SELECTED -eq 0
        printf '%s' "$_TABRA_RENDERED_POPUP"
        return
    end

    # Fallback: basic rendering
    printf '\n'
    for i in (seq $visible)
        set -l display $_TABRA_DISPLAYS[$i]
        set -l desc $_TABRA_DESCS[$i]
        set -l idx (math "$i - 1")

        if test $idx -eq $_TABRA_SELECTED
            if test -n "$desc"
                printf '\r\033[7m %s  \033[2m%s\033[22m \033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r\033[7m %s \033[0m\033[K\n' "$display"
            end
        else
            if test -n "$desc"
                printf '\r  %s  \033[90m%s\033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r  %s \033[K\n' "$display"
            end
        end
    end
    printf "\033[%dA" (math "$visible + 1")
end

# Fetch completions and render
function _tabra_fetch_and_render
    set -l buffer (commandline --current-buffer)
    set -l cursor (commandline --cursor)

    set -l response (tabra complete-shell --buffer "$buffer" --cursor "$cursor" --cwd "$PWD" --cols "$COLUMNS" --render 2>/dev/null)

    if test -z "$response"
        _tabra_erase_popup
        set -g _TABRA_ITEM_COUNT 0
        set -g _TABRA_RENDERED_POPUP ""
        return
    end

    set -g _TABRA_SELECTED 0

    # Split on double newline: items section and rendered popup
    set -l joined (string join \n -- $response)
    set -l parts (string split \n\n -- $joined)
    set -l items_section $parts[1]
    if test (count $parts) -ge 2
        set -g _TABRA_RENDERED_POPUP $parts[2]
    else
        set -g _TABRA_RENDERED_POPUP ""
    end

    _tabra_parse_response "$items_section"

    if test $_TABRA_ITEM_COUNT -eq 0
        _tabra_erase_popup
        return
    end

    _tabra_render_popup
end

# Accept the selected suggestion
function _tabra_accept
    if test $_TABRA_POPUP_VISIBLE -eq 1; and test $_TABRA_ITEM_COUNT -gt 0
        set -l idx (math "$_TABRA_SELECTED + 1")
        set -l insert_text $_TABRA_INSERTS[$idx]
        if test -n "$insert_text"
            # Get current token and replace it
            set -l token (commandline --current-token)
            commandline --current-token -- "$insert_text "
            tabra accept --text "$insert_text" &>/dev/null &
            disown
        end
        _tabra_erase_popup
        set -g _TABRA_ITEM_COUNT 0
    end
end

# Navigate up
function _tabra_up
    if test $_TABRA_POPUP_VISIBLE -eq 1
        set -g _TABRA_SELECTED (math "($_TABRA_SELECTED - 1 + $_TABRA_ITEM_COUNT) % $_TABRA_ITEM_COUNT")
        _tabra_render_popup
    else
        up-or-search
    end
end

# Navigate down
function _tabra_down
    if test $_TABRA_POPUP_VISIBLE -eq 1
        set -g _TABRA_SELECTED (math "($_TABRA_SELECTED + 1) % $_TABRA_ITEM_COUNT")
        _tabra_render_popup
    else
        down-or-search
    end
end

# Dismiss popup
function _tabra_dismiss
    if test $_TABRA_POPUP_VISIBLE -eq 1
        _tabra_erase_popup
        set -g _TABRA_ITEM_COUNT 0
        tabra dismiss &>/dev/null &
        disown
    end
end

# Self-insert wrapper: type character then fetch completions
function _tabra_self_insert
    commandline -i -- (string join '' -- $argv)
    _tabra_fetch_and_render
end

# Backward delete with popup update
function _tabra_backward_delete
    commandline -f backward-delete-char
    if test -n (commandline --current-buffer)
        _tabra_fetch_and_render
    else
        _tabra_erase_popup
        set -g _TABRA_ITEM_COUNT 0
    end
end

# Key bindings
bind \t _tabra_accept
bind \e\[A _tabra_up
bind \e\[B _tabra_down
bind \e _tabra_dismiss
bind \x7f _tabra_backward_delete

# Bind printable characters
for c in a b c d e f g h i j k l m n o p q r s t u v w x y z \
         A B C D E F G H I J K L M N O P Q R S T U V W X Y Z \
         0 1 2 3 4 5 6 7 8 9 \
         - . / _ '~' : = + @ '!' '#' '%' ' '
    bind $c "_tabra_self_insert $c"
end

# Ensure daemon on startup
_tabra_ensure_daemon

# Cleanup on exit
function _tabra_cleanup --on-event fish_exit
    _tabra_erase_popup
end
"##
    .to_string()
}
