//! Shell hook scripts.
//!
//! The zsh hook integrates with ZLE (Zsh Line Editor) to:
//!
//! 1. Intercept keystrokes via a ZLE widget
//! 2. On each keystroke, call `tabra complete-shell` which returns tab-delimited output
//! 3. Parse the simple line-per-item format (no JSON, no jq, no python3)
//! 4. Render the popup overlay below the prompt using ANSI escapes
//! 5. Handle Tab (accept), Escape (dismiss), Up/Down (navigate)
//! 6. On accept, insert the selected text into BUFFER and redisplay
//!
//! The hook script is printed to stdout and eval'd by the user's .zshrc:
//!   eval "$(tabra init zsh)"

/// Generate the zsh hook script.
pub fn zsh_hook() -> String {
    r##"
# ============================================================================
# Tabra - Terminal Autocomplete Hook for Zsh
# Generated by: tabra init zsh
# Add to .zshrc: eval "$(tabra init zsh)"
# ============================================================================

# Guard against double-sourcing
[[ -n "$_TABRA_LOADED" ]] && return
_TABRA_LOADED=1

# State variables
typeset -g _TABRA_POPUP_VISIBLE=0
typeset -g _TABRA_POPUP_LINES=0
typeset -g _TABRA_SELECTED=0
typeset -g _TABRA_ITEM_COUNT=0
# Parallel arrays (parsed from tab-delimited daemon output)
typeset -ga _TABRA_DISPLAYS=()
typeset -ga _TABRA_INSERTS=()
typeset -ga _TABRA_DESCS=()

# Ensure daemon is running (start if not)
_tabra_ensure_daemon() {
    tabra status &>/dev/null && return
    tabra daemon &>/dev/null &!
    local i
    for i in 1 2 3 4 5; do
        sleep 0.1
        tabra status &>/dev/null && return
    done
}

# Erase the popup overlay
_tabra_erase_popup() {
    if (( _TABRA_POPUP_VISIBLE )); then
        local i
        for (( i = 0; i < _TABRA_POPUP_LINES + 2; i++ )); do
            printf '\n\r\033[2K'
        done
        printf "\033[%dA" $(( _TABRA_POPUP_LINES + 2 ))
        _TABRA_POPUP_VISIBLE=0
        _TABRA_POPUP_LINES=0
    fi
}

# Parse daemon output into parallel arrays.
# Format from `tabra complete-shell`:
#   Line 1: item count (integer)
#   Lines 2+: display\tinsert\tdescription (tab-separated)
# No JSON. No regex. Just IFS splitting on tabs.
_tabra_parse_response() {
    _TABRA_DISPLAYS=()
    _TABRA_INSERTS=()
    _TABRA_DESCS=()
    _TABRA_ITEM_COUNT=0

    local -a lines
    lines=("${(@f)1}")

    # First line is the count
    (( ${#lines[@]} < 1 )) && return
    _TABRA_ITEM_COUNT=${lines[1]}
    (( _TABRA_ITEM_COUNT == 0 )) && return

    # Parse each subsequent line
    local i
    for (( i = 2; i <= ${#lines[@]} && i <= _TABRA_ITEM_COUNT + 1; i++ )); do
        local line="${lines[$i]}"
        # Split on tab
        local display="${line%%	*}"
        local rest="${line#*	}"
        local insert="${rest%%	*}"
        local desc="${rest#*	}"
        # If no second tab, desc is same as insert (no description)
        [[ "$desc" == "$insert" ]] && desc=""

        _TABRA_DISPLAYS+=("$display")
        _TABRA_INSERTS+=("$insert")
        _TABRA_DESCS+=("$desc")
    done
}

# Render the popup from cached arrays (no daemon call)
_tabra_render_popup() {
    _tabra_erase_popup

    (( _TABRA_ITEM_COUNT == 0 )) && return

    _TABRA_POPUP_VISIBLE=1
    # Show at most 10 items
    local visible=$(( _TABRA_ITEM_COUNT < 10 ? _TABRA_ITEM_COUNT : 10 ))
    _TABRA_POPUP_LINES=$visible

    printf '\n'
    local i
    for (( i = 1; i <= visible; i++ )); do
        local display="${_TABRA_DISPLAYS[$i]}"
        local desc="${_TABRA_DESCS[$i]}"

        if (( i - 1 == _TABRA_SELECTED )); then
            if [[ -n "$desc" ]]; then
                printf '\r\033[7m %s  \033[2m%s\033[22m \033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r\033[7m %s \033[0m\033[K\n' "$display"
            fi
        else
            if [[ -n "$desc" ]]; then
                printf '\r  %s  \033[90m%s\033[0m\033[K\n' "$display" "$desc"
            else
                printf '\r  %s \033[K\n' "$display"
            fi
        fi
    done
    printf "\033[%dA" $(( visible + 1 ))
}

# Fetch completions from daemon and render
_tabra_fetch_and_render() {
    local response
    response=$(tabra complete-shell --buffer "$BUFFER" --cursor "$CURSOR" --cwd "$PWD" 2>/dev/null)

    if [[ -z "$response" ]]; then
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
        return
    fi

    _TABRA_SELECTED=0
    _tabra_parse_response "$response"

    if (( _TABRA_ITEM_COUNT == 0 )); then
        _tabra_erase_popup
        return
    fi

    _tabra_render_popup
}

# Accept the currently selected suggestion
_tabra_accept() {
    if (( _TABRA_POPUP_VISIBLE && _TABRA_ITEM_COUNT > 0 )); then
        local insert_text="${_TABRA_INSERTS[$(( _TABRA_SELECTED + 1 ))]}"
        if [[ -n "$insert_text" ]]; then
            # Find the current token boundary by forward-walking through before_cursor
            # (forward walk handles quotes correctly, unlike backwards walk)
            local before_cursor="${BUFFER:0:$CURSOR}"
            local after_cursor="${BUFFER:$CURSOR}"
            local token_start=0

            # Forward walk to find the start of the last token
            local -i i=0 last_boundary=0
            local in_sq=0 in_dq=0 escape_next=0
            local ch
            while (( i < ${#before_cursor} )); do
                ch="${before_cursor:$i:1}"
                if (( escape_next )); then
                    (( escape_next = 0 ))
                elif [[ "$ch" == '\' ]] && (( !in_sq )); then
                    (( escape_next = 1 ))
                elif [[ "$ch" == "'" ]] && (( !in_dq )); then
                    (( in_sq = !in_sq ))
                elif [[ "$ch" == '"' ]] && (( !in_sq )); then
                    (( in_dq = !in_dq ))
                elif [[ "$ch" == ' ' || "$ch" == $'\t' ]] && (( !in_sq && !in_dq )); then
                    last_boundary=$(( i + 1 ))
                fi
                (( i++ ))
            done
            token_start=$last_boundary

            BUFFER="${BUFFER:0:$token_start}${insert_text} ${after_cursor}"
            CURSOR=$(( token_start + ${#insert_text} + 1 ))
            tabra accept --text "$insert_text" &>/dev/null &!
        fi
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
    fi
}

# Navigate up in the popup (re-render only, no daemon call)
_tabra_up() {
    if (( _TABRA_POPUP_VISIBLE )); then
        (( _TABRA_SELECTED = (_TABRA_SELECTED - 1 + _TABRA_ITEM_COUNT) % _TABRA_ITEM_COUNT ))
        _tabra_render_popup
    else
        zle up-line-or-history
    fi
}

# Navigate down in the popup (re-render only, no daemon call)
_tabra_down() {
    if (( _TABRA_POPUP_VISIBLE )); then
        (( _TABRA_SELECTED = (_TABRA_SELECTED + 1) % _TABRA_ITEM_COUNT ))
        _tabra_render_popup
    else
        zle down-line-or-history
    fi
}

# Dismiss the popup
_tabra_dismiss() {
    if (( _TABRA_POPUP_VISIBLE )); then
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
        tabra dismiss &>/dev/null &!
    else
        zle send-break
    fi
}

# Main widget: called on every self-insert keystroke
_tabra_self_insert() {
    zle .self-insert
    _tabra_fetch_and_render
}

# Backward delete with popup update
_tabra_backward_delete() {
    zle .backward-delete-char
    if [[ -n "$BUFFER" ]]; then
        _tabra_fetch_and_render
    else
        _tabra_erase_popup
        _TABRA_ITEM_COUNT=0
    fi
}

# Register ZLE widgets
zle -N _tabra_self_insert
zle -N _tabra_backward_delete
zle -N _tabra_accept
zle -N _tabra_up
zle -N _tabra_down
zle -N _tabra_dismiss

# Bind keys
bindkey -M main '\t' _tabra_accept          # Tab: accept
bindkey -M main '^[[A' _tabra_up             # Up arrow: navigate up
bindkey -M main '^[[B' _tabra_down           # Down arrow: navigate down
bindkey -M main '^[' _tabra_dismiss          # Escape: dismiss
bindkey -M main '^?' _tabra_backward_delete  # Backspace: delete + refresh

# Override self-insert to trigger completions on each keystroke
() {
    local -a keys
    keys=({a..z} {A..Z} {0..9} '-' '_' '.' '/' '~' ':' '=' '+' '@' '!' '#' '%')
    local key
    for key in "${keys[@]}"; do
        bindkey -M main "$key" _tabra_self_insert
    done
    bindkey -M main ' ' _tabra_self_insert
}

# Ensure daemon on shell startup
_tabra_ensure_daemon

# Cleanup on shell exit
_tabra_cleanup() {
    _tabra_erase_popup
}
add-zsh-hook zshexit _tabra_cleanup 2>/dev/null || true
"##
    .to_string()
}
